services:
  web-cli:
    build: .
    ports:
      - "${FLASK_RUN_PORT}:${FLASK_RUN_PORT}"
    volumes:
      - .:/app
      - /app/.venv
    environment:
      - NODE_ENV=production
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
