version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    command: gunicorn --worker-class gevent --workers 2 --bind 0.0.0.0:3003 --timeout 300 --reload app:app
